// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PingAI.DialogManagementService.Domain.Model;
using PingAI.DialogManagementService.Infrastructure.Persistence;

namespace PingAI.DialogManagementService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DialogManagementContext))]
    [Migration("20210606072046_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresEnum("chatbot", "enum_ChatHistories_session_status", new[] { "CHATBOT", "HANDOVER" })
                .HasPostgresEnum("chatbot", "enum_Intents_type", new[] { "STANDARD", "GENERIC" })
                .HasPostgresEnum("chatbot", "enum_PhraseParts_type", new[] { "CONSTANT_ENTITY", "ENTITY", "TEXT" })
                .HasPostgresEnum("chatbot", "enum_Response_type", new[] { "RTE", "HANDOVER", "VIDEO", "SOCIAL", "WEBHOOK", "FORM", "QUICK_REPLY" })
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 933, DateTimeKind.Utc).AddTicks(5090))
                        .HasColumnName("createdAt");

                    b.Property<string>("Input")
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("requestId");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessionId");

                    b.Property<SessionStatus>("SessionStatus")
                        .HasColumnType("chatbot.\"enum_ChatHistories_session_status\"")
                        .HasColumnName("sessionStatus");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 933, DateTimeKind.Utc).AddTicks(5320))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("ChatHistories", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.EntityName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanBeReferenced")
                        .HasColumnType("boolean")
                        .HasColumnName("canBeReferenced");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 937, DateTimeKind.Utc).AddTicks(640))
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 937, DateTimeKind.Utc).AddTicks(1360))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EntityNames", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 942, DateTimeKind.Utc).AddTicks(3750))
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 942, DateTimeKind.Utc).AddTicks(4520))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EntityTypes", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.EntityValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 944, DateTimeKind.Utc).AddTicks(3200))
                        .HasColumnName("createdAt");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityTypeId");

                    b.Property<string[]>("Synonyms")
                        .HasColumnType("text[]")
                        .HasColumnName("synonyms");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 944, DateTimeKind.Utc).AddTicks(3650))
                        .HasColumnName("updatedAt");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("EntityValues", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.GreetingResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 947, DateTimeKind.Utc).AddTicks(9820))
                        .HasColumnName("createdAt");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("responseId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 948, DateTimeKind.Utc).AddTicks(80))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResponseId");

                    b.ToTable("GreetingResponses", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Intent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 953, DateTimeKind.Utc).AddTicks(2760))
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<IntentType>("Type")
                        .HasColumnType("chatbot.\"enum_Intents_type\"")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 953, DateTimeKind.Utc).AddTicks(3460))
                        .HasColumnName("updatedAt");

                    b.Property<string>("_color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("_iconName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iconName");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Intents", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 956, DateTimeKind.Utc).AddTicks(6510))
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 956, DateTimeKind.Utc).AddTicks(7520))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Organisations", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.OrganisationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 959, DateTimeKind.Utc).AddTicks(8960))
                        .HasColumnName("createdAt");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisationId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 959, DateTimeKind.Utc).AddTicks(9580))
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganisationUsers", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.PhrasePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 964, DateTimeKind.Utc).AddTicks(9310))
                        .HasColumnName("createdAt");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayOrder");

                    b.Property<Guid?>("EntityNameId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityNameId");

                    b.Property<Guid?>("EntityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityTypeId");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intentId");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phraseId");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<PhrasePartType>("Type")
                        .HasColumnType("chatbot.\"enum_PhraseParts_type\"")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 965, DateTimeKind.Utc).AddTicks(200))
                        .HasColumnName("updatedAt");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EntityNameId");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("IntentId");

                    b.ToTable("PhraseParts", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("text")
                        .HasColumnName("businessEmail");

                    b.Property<DateTime?>("BusinessTimeEndUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("businessTimeEndUtc");

                    b.Property<DateTime?>("BusinessTimeStartUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("businessTimeStartUtc");

                    b.Property<string>("BusinessTimezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("businessTimezone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 982, DateTimeKind.Utc).AddTicks(6360))
                        .HasColumnName("createdAt");

                    b.Property<string[]>("Domains")
                        .HasColumnType("text[]")
                        .HasColumnName("domains");

                    b.Property<string[]>("Enquiries")
                        .HasColumnType("text[]")
                        .HasColumnName("enquiries");

                    b.Property<string>("FallbackMessage")
                        .HasColumnType("text")
                        .HasColumnName("fallbackMessage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisationId");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 982, DateTimeKind.Utc).AddTicks(8390))
                        .HasColumnName("updatedAt");

                    b.Property<string>("WidgetColor")
                        .HasColumnType("text")
                        .HasColumnName("widgetColor");

                    b.Property<string>("WidgetDescription")
                        .HasColumnType("text")
                        .HasColumnName("widgetDescription");

                    b.Property<string>("WidgetTitle")
                        .HasColumnType("text")
                        .HasColumnName("widgetTitle");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Projects", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.ProjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 997, DateTimeKind.Utc).AddTicks(5740))
                        .HasColumnName("createdAt");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisationId");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 997, DateTimeKind.Utc).AddTicks(6360))
                        .HasColumnName("updatedAt");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("VersionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("versionGroupId");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectVersions", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Query", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 9, DateTimeKind.Utc).AddTicks(7290))
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayOrder");

                    b.Property<Expression[]>("Expressions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("expressions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 9, DateTimeKind.Utc).AddTicks(7810))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Queries", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 16, DateTimeKind.Utc).AddTicks(2830))
                        .HasColumnName("createdAt");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resolution");

                    b.Property<string>("SpeechContexts")
                        .HasColumnType("jsonb")
                        .HasColumnName("speechContexts");

                    b.Property<ResponseType>("Type")
                        .HasColumnType("chatbot.\"enum_Response_type\"")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 16, DateTimeKind.Utc).AddTicks(3800))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Responses", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.SlackWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 18, DateTimeKind.Utc).AddTicks(2730))
                        .HasColumnName("createdAt");

                    b.Property<string>("OAuthAccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oauthAccessToken");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("teamId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 18, DateTimeKind.Utc).AddTicks(3210))
                        .HasColumnName("updatedAt");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("webhookURL");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SlackWorkspaces", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth0Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 19, DateTimeKind.Utc).AddTicks(2700))
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 46, 19, DateTimeKind.Utc).AddTicks(3240))
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Users", "chatbot");
                });

            modelBuilder.Entity("QueryIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 913, DateTimeKind.Utc).AddTicks(2030))
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 914, DateTimeKind.Utc).AddTicks(8750))
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("intentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("queryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("intentId");

                    b.HasIndex("queryId");

                    b.ToTable("QueryIntents", "chatbot");
                });

            modelBuilder.Entity("QueryResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 915, DateTimeKind.Utc).AddTicks(8530))
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 6, 6, 7, 20, 45, 915, DateTimeKind.Utc).AddTicks(8770))
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("queryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("responseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("queryId");

                    b.HasIndex("responseId");

                    b.ToTable("QueryResponses", "chatbot");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.EntityName", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithMany("EntityNames")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.EntityType", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithMany("EntityTypes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.EntityValue", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.EntityType", "EntityType")
                        .WithMany("Values")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.GreetingResponse", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithMany("GreetingResponses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Response", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Intent", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithMany("Intents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.OrganisationUser", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Organisation", "Organisation")
                        .WithMany("OrganisationUsers")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.User", "User")
                        .WithMany("OrganisationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.PhrasePart", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.EntityName", "EntityName")
                        .WithMany()
                        .HasForeignKey("EntityNameId");

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId");

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Intent", "Intent")
                        .WithMany("PhraseParts")
                        .HasForeignKey("IntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityName");

                    b.Navigation("EntityType");

                    b.Navigation("Intent");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Project", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Organisation", "Organisation")
                        .WithMany("Projects")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Response", null)
                        .WithMany("GreetingProjects")
                        .HasForeignKey("ResponseId");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.ProjectVersion", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Organisation", "Organisation")
                        .WithMany("ProjectVersions")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithOne("ProjectVersion")
                        .HasForeignKey("PingAI.DialogManagementService.Domain.Model.ProjectVersion", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Query", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithMany("Queries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Response", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithMany("Responses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.SlackWorkspace", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("QueryIntent", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Intent", null)
                        .WithMany()
                        .HasForeignKey("intentId")
                        .HasConstraintName("QueryIntents_intentId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Query", null)
                        .WithMany()
                        .HasForeignKey("queryId")
                        .HasConstraintName("QueryIntents_queryId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QueryResponse", b =>
                {
                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Query", null)
                        .WithMany()
                        .HasForeignKey("queryId")
                        .HasConstraintName("QueryResponses_queryId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PingAI.DialogManagementService.Domain.Model.Response", null)
                        .WithMany()
                        .HasForeignKey("responseId")
                        .HasConstraintName("QueryResponses_responseId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.EntityType", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Intent", b =>
                {
                    b.Navigation("PhraseParts");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Organisation", b =>
                {
                    b.Navigation("OrganisationUsers");

                    b.Navigation("Projects");

                    b.Navigation("ProjectVersions");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Project", b =>
                {
                    b.Navigation("EntityNames");

                    b.Navigation("EntityTypes");

                    b.Navigation("GreetingResponses");

                    b.Navigation("Intents");

                    b.Navigation("ProjectVersion")
                        .IsRequired();

                    b.Navigation("Queries");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.Response", b =>
                {
                    b.Navigation("GreetingProjects");
                });

            modelBuilder.Entity("PingAI.DialogManagementService.Domain.Model.User", b =>
                {
                    b.Navigation("OrganisationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
